vocab:
    vocab_size: 5000
    pad_id: 0
    unk_id: 1
    bos_id: 2
    eos_id: 3
    pad_token: "[PAD]"
    unk_token: "[UNK]"
    bos_token: "[BOS]"
    eos_token: "[EOS]"


model:
    emb_dim: 256
    hidden_dim: 256
    pff_dim: 512
    n_layers: 3
    n_heads: 8
    dropout_ratio: 0.1


train:
    n_epochs: 10
    batch_size: 128
    lr: 0.0005
    early_stop: 1
    patience: 3
    clip: 1
    iters_to_accumulate: 4
    max_len: 512